### ISSUE TITLE
Release latest changes to bevy_aseprite_derive

### ISSUE THREAD

**Issue by jutsuu** [mdenchev/bevy_aseprite#11]
Hey, could you make a new release of `bevy_aseprite_derive` in crates.io with the changes in #4?
I'm using another crate that depends on `bevy_aseprite_derive` and I'm having the same issue as the description of that PR. 
The changes are merged but they're not released. Since it's another repo using it and not `bevy_aseprite` with `path="..."`, I don't get the changes.

Thanks for this repo, I've been using it a bunch in my pet projects.

**Comment by mdenchev** [comment]
Hey jutsuu, no problem, published the changed.
