### ISSUE TITLE
Blank frames cause panic

### ISSUE THREAD

**Issue by NitroPlum** [mdenchev/bevy_aseprite#7]
If an animation has any empty frames on any visible layer, the game will crash. It's common to have empty frames separating animations in Aseprite to prevent ugly tag-stacking that can occur in bigger files. Here is an example of a timeline that would cause a crash. I also tested with a minimal example that also had the same issue : 

![cffb38724488d731630ebcb982312781](https://user-images.githubusercontent.com/61946695/200062295-fe65166b-f352-444e-b42a-09f8d42bbe01.png)

**Comment by EduardoRodriguesF** [comment]
Having a similar issue, the game crashes if the Aseprite file contains any grouping.

![image](https://user-images.githubusercontent.com/44787022/212477995-88dfa1cc-eeea-47c0-9652-b2900bebeeb6.png)

**Comment by upachler** [comment]
Hi, I can confirm that this fix appears to work; the sprite that I could not load with the official bevy_asprite 0.9 is loading fine with this fix.

**Comment by mdenchev** [comment]
Thanks @NoahShomette for the fix and @upachler confirming.
